app:
  name: newsservice
  read_timeout: 10
  write_timeout: 10
  connect_timeout: 10
  processing_interval: 3
  feed_urls:
    - name: dev.to
      url: https://dev.to/feed
    - name: bbci.com
      url: http://feeds.bbci.co.uk/news/rss.xml
    - name: nytimes.com
      url: https://rss.nytimes.com/services/xml/rss/nyt/World.xml
    - name: ria.ru
      url: https://ria.ru/export/rss2/index.xml

http:
  host: 0.0.0.0
  port: 6000

logging:
  level: debug
  format: text

db:
  host: postgres-news
  port: "5432"
  username: news
  password: password
  db_name: newsservice
  sslmode: disable

kafka:
  brokers:
    - kafka:9093
  topics:
    news_input: news_input
    news_list: news_list
    news_detail: news_detail
    filtered_content: filtered_content
    filter_published: filter_published
  consumer_groups:
    gnews: gnews
    api_gateway: api_gateway

service:
  address: ":6000"

routes:
  - name: apigateway
    base_url: http://apigateway:8080
  - name: commentservice
    base_url: http://commentservice:8081    