app:
  name: newsservice
  read_timeout: 10
  write_timeout: 10
  connect_timeout: 10
  processing_interval: "3m"
  feed_urls:
    - name: dev.to
      url: https://dev.to/feed
    - name: bbci.com
      url: http://feeds.bbci.co.uk/news/rss.xml
    - name: nytimes.com
      url: https://rss.nytimes.com/services/xml/rss/nyt/World.xml
    - name: ria.ru
      url: https://ria.ru/export/rss2/index.xml

http:
  host: 0.0.0.0
  port: :6000

logging:
  level: debug
  format: text

database:
  host: localhost
  port: 5432
  username: news
  password: password
  db_name: newsservice
  sslmode: disable

kafka:
  brokers:
    - localhost: 9092
  topics:
    news_input: news_input
    news_list: news_list
    news_detail: news_detail
    filtered_content: filtered_content
    filter_published: filter_published
  consumer_groups:
  api_ateway: api_gateway

service:
  address: ":6000"

routes:
  - name: apigateway
    base_url: http://localhot:8080
  - name: commentservice
    base_url: http://localhost:7000    