app:
  name: ${APP_NAME}
  env: ${APP_ENV}
  version: ${APP_VERSION}
  read_timeout: 10
  write_timeout: 10
  connect_timeout: 10
  processing_interval: "3m"
  feed_urls:
    - url: "https://dev.to/feed"
      name: "Dev.to"
    - url: "https://ria.ru/export/rss2/index.xml"
      name: "RIA"
    - url: "https://www.kommersant.ru/RSS/news.xml"
      name: "Kommersant"

http:
  host: ${HTTP_HOST}
  port: ${HTTP_PORT}

database:
  host: ${DB_HOST
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  sslmode: disable

logging:
  level: ${LOGGING_LEVEL}
  format: ${LOGGING_FORMAT}

routes:
 - name: commentservice
   base_url: http://localhost:7000
 - name: apigateway
   base_url: http://localhost:5000
 - name: censor
   base_url: http:// localhost: 